import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F3F8FA',
  },
  keyboardView: {
    flex: 1,
  },
  loginContent: {
    backgroundColor: '#F4F7FB',
    flexGrow: 1,
    gap: 18,
    justifyContent: 'center',
    padding: 24,
  },
  loginDecorTop: {
    display: 'none',
  },
  loginDecorBottom: {
    display: 'none',
  },
  content: {
    gap: 14,
    padding: 14,
    paddingBottom: 32,
  },
  screenContent: {
    gap: 14,
    padding: 14,
    paddingBottom: 24,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  logoMark: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D9E4EC',
    borderWidth: 1,
    borderRadius: 8,
    height: 46,
    justifyContent: 'center',
    shadowColor: '#102A43',
    shadowOffset: {
      height: 3,
      width: 0,
    },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    width: 46,
  },
  logoText: {
    color: '#1A6F8F',
    fontSize: 22,
    fontWeight: '900',
  },
  brandName: {
    color: '#162033',
    fontSize: 17,
    fontWeight: '900',
  },
  brandMeta: {
    color: '#6B7A90',
    fontSize: 13,
    marginTop: 2,
  },
  loginHero: {
    gap: 12,
  },
  kicker: {
    color: '#1A6F8F',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  title: {
    color: '#101828',
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 36,
  },
  subtitle: {
    color: '#667085',
    fontSize: 15,
    lineHeight: 22,
  },
  loginTitleBlock: {
    gap: 8,
  },
  loginStatusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  loginPill: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E0E8EF',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  loginPillText: {
    color: '#344054',
    fontSize: 12,
    fontWeight: '800',
  },
  loginChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingTop: 2,
  },
  loginChip: {
    backgroundColor: 'rgba(53,242,167,0.12)',
    borderColor: 'rgba(53,242,167,0.32)',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  loginChipText: {
    color: '#D9FFF0',
    fontSize: 12,
    fontWeight: '900',
  },
  loginPanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E0E8EF',
    borderRadius: 8,
    borderWidth: 1,
    elevation: 3,
    gap: 18,
    padding: 18,
    shadowColor: '#102A43',
    shadowOffset: {
      height: 6,
      width: 0,
    },
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  authHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  authEyebrow: {
    color: '#667085',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  authTitle: {
    color: '#101828',
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 34,
    marginTop: 3,
  },
  authBackButton: {
    backgroundColor: '#F2F6FA',
    borderColor: '#E0E8EF',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  authBackButtonText: {
    color: '#1A6F8F',
    fontSize: 13,
    fontWeight: '900',
  },
  trustBadgeRow: {
    flexDirection: 'row',
    gap: 10,
  },
  trustBadge: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E7EC',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 54,
    paddingHorizontal: 10,
  },
  trustBadgeDot: {
    backgroundColor: '#A7B3BA',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  trustBadgeDotActive: {
    backgroundColor: '#35F2A7',
  },
  trustBadgeLabel: {
    color: '#667085',
    fontSize: 11,
    fontWeight: '800',
  },
  trustBadgeValue: {
    color: '#1D2939',
    fontSize: 13,
    fontWeight: '900',
    marginTop: 2,
  },
  authForm: {
    gap: 12,
  },
  sentToBox: {
    backgroundColor: '#F6FAFC',
    borderColor: '#E0E8EF',
    borderRadius: 8,
    borderWidth: 1,
    gap: 3,
    padding: 12,
  },
  sentToLabel: {
    color: '#667085',
    fontSize: 12,
    fontWeight: '800',
  },
  sentToEmail: {
    color: '#101828',
    fontSize: 15,
    fontWeight: '900',
  },
  googleButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E2EA',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  googleButtonDisabled: {
    backgroundColor: '#F0F4F8',
  },
  googleMark: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E3E8EF',
    borderRadius: 8,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  googleMarkText: {
    color: '#1A73E8',
    fontSize: 15,
    fontWeight: '900',
  },
  googleButtonText: {
    color: '#162033',
    fontSize: 14,
    fontWeight: '900',
  },
  loginDivider: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  loginDividerLine: {
    backgroundColor: '#E4EAF0',
    flex: 1,
    height: 1,
  },
  loginDividerText: {
    color: '#7B8794',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  otpWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    minHeight: 54,
    position: 'relative',
  },
  otpHiddenInput: {
    height: 1,
    opacity: 0.01,
    position: 'absolute',
    width: 1,
  },
  otpCell: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#D7E2EA',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    height: 52,
    justifyContent: 'center',
  },
  otpCellActive: {
    borderColor: '#1A6F8F',
    borderWidth: 2,
  },
  otpCellFilled: {
    backgroundColor: '#EAF6F9',
    borderColor: '#77BFD0',
  },
  otpDigit: {
    color: '#101828',
    fontSize: 21,
    fontWeight: '900',
    lineHeight: 25,
  },
  authLinkRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  authTextButton: {
    borderRadius: 8,
    paddingHorizontal: 2,
    paddingVertical: 6,
  },
  authTextButtonText: {
    color: '#1A6F8F',
    fontSize: 13,
    fontWeight: '900',
  },
  loginMessageBox: {
    backgroundColor: '#EAF1F6',
    borderColor: '#D7E2EA',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  loginErrorText: {
    color: '#B42318',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },
  appHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 8,
  },
  walletHero: {
    backgroundColor: '#0F8EA3',
    borderRadius: 8,
    gap: 18,
    overflow: 'hidden',
    padding: 16,
  },
  heroTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  menuButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  menuButtonText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 22,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  heroSubtitle: {
    color: '#CDEEF2',
    fontSize: 12,
    marginTop: 2,
  },
  portfolioBlock: {
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
  },
  heroActions: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 8,
  },
  heroAction: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    gap: 4,
    minHeight: 66,
    justifyContent: 'center',
  },
  heroActionIcon: {
    color: '#1097A7',
    fontSize: 21,
    fontWeight: '900',
    lineHeight: 22,
  },
  heroActionText: {
    color: '#29495A',
    fontSize: 12,
    fontWeight: '900',
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#E9F6EF',
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  avatarText: {
    color: '#127D46',
    fontSize: 18,
    fontWeight: '900',
  },
  headerCopy: {
    flex: 1,
  },
  accountEmail: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  networkText: {
    color: '#A7B0BA',
    fontSize: 13,
    marginTop: 2,
  },
  logoutButton: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  logoutText: {
    color: '#F4F7F5',
    fontSize: 13,
    fontWeight: '800',
  },
  balanceCard: {
    backgroundColor: '#DDF5E6',
    borderRadius: 8,
    gap: 8,
    padding: 18,
  },
  balanceLabel: {
    color: '#CDEEF2',
    fontSize: 13,
    fontWeight: '800',
  },
  balanceValue: {
    color: '#FFFFFF',
    fontSize: 36,
    fontWeight: '900',
    letterSpacing: 0,
  },
  balanceHint: {
    color: '#DDF6F8',
    fontSize: 13,
  },
  panel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 12,
    padding: 14,
  },
  sectionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionHeading: {
    color: '#24495A',
    fontSize: 17,
    fontWeight: '900',
  },
  sectionHint: {
    color: '#7E909A',
    fontSize: 12,
    fontWeight: '800',
  },
  rowBetween: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  infoLine: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  label: {
    color: '#667085',
    fontSize: 13,
    fontWeight: '800',
  },
  value: {
    color: '#111827',
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  helper: {
    color: '#344054',
    fontSize: 13,
    lineHeight: 20,
  },
  smallText: {
    color: '#667085',
    fontSize: 12,
    lineHeight: 17,
  },
  inputLabel: {
    color: '#253142',
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    backgroundColor: '#F1F7F9',
    borderColor: '#D8E7EC',
    borderRadius: 8,
    borderWidth: 1,
    color: '#111827',
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  addressInput: {
    fontSize: 13,
  },
  addressBox: {
    backgroundColor: '#F1F7F9',
    borderRadius: 8,
    padding: 12,
  },
  addressText: {
    color: '#2B3548',
    fontSize: 12,
    lineHeight: 18,
  },
  quickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 6,
  },
  assetRow: {
    alignItems: 'center',
    borderColor: '#E4EEF2',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 12,
  },
  assetBadge: {
    alignItems: 'center',
    backgroundColor: '#E6F7F2',
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  assetBadgeText: {
    color: '#11C779',
    fontSize: 17,
    fontWeight: '900',
  },
  assetCopy: {
    flex: 1,
    gap: 3,
  },
  assetCode: {
    color: '#24495A',
    fontSize: 15,
    fontWeight: '900',
  },
  assetMeta: {
    color: '#667085',
    fontSize: 12,
  },
  assetRight: {
    alignItems: 'flex-end',
    gap: 8,
  },
  assetBalance: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '900',
  },
  inlineButton: {
    backgroundColor: '#E5FAF1',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  inlineButtonText: {
    color: '#0ABF73',
    fontSize: 12,
    fontWeight: '900',
  },
  inlineGhostButton: {
    borderColor: '#D8E7EC',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  inlineGhostButtonText: {
    color: '#24495A',
    fontSize: 12,
    fontWeight: '900',
  },
  assetTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  assetTab: {
    backgroundColor: '#F1F7F9',
    borderColor: '#D8E7EC',
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 72,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  assetTabSelected: {
    backgroundColor: '#0F8EA3',
    borderColor: '#0F8EA3',
  },
  assetTabText: {
    color: '#344054',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  assetTabTextSelected: {
    color: '#FFFFFF',
  },
  noticeBox: {
    backgroundColor: '#FFF7E8',
    borderColor: '#FEDF89',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  button: {
    alignItems: 'center',
    borderRadius: 8,
    flexGrow: 1,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  primaryButton: {
    backgroundColor: '#0ABF73',
  },
  secondaryButton: {
    backgroundColor: '#E5FAF1',
  },
  disabledButton: {
    backgroundColor: '#D8DEE9',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
  },
  secondaryButtonText: {
    color: '#0ABF73',
  },
  disabledButtonText: {
    color: '#7B8494',
  },
  recipientBox: {
    backgroundColor: '#F1F7F9',
    borderColor: '#D8E7EC',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  linkText: {
    color: '#0F8EA3',
    fontSize: 13,
    fontWeight: '900',
  },
  emptyState: {
    backgroundColor: '#F1F7F9',
    borderRadius: 8,
    gap: 6,
    padding: 14,
  },
  emptyTitle: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '900',
  },
  emptyText: {
    color: '#667085',
    fontSize: 13,
    lineHeight: 19,
  },
  transactionRow: {
    alignItems: 'center',
    borderBottomColor: '#E4EEF2',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 12,
  },
  txIcon: {
    alignItems: 'center',
    backgroundColor: '#FFEDEF',
    borderRadius: 8,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  txIconReceived: {
    backgroundColor: '#E5FAF1',
  },
  txIconTrustline: {
    backgroundColor: '#EAF7FA',
  },
  txIconText: {
    color: '#0ABF73',
    fontSize: 18,
    fontWeight: '900',
  },
  txBody: {
    flex: 1,
    gap: 3,
  },
  txTitle: {
    color: '#24495A',
    fontSize: 14,
    fontWeight: '900',
  },
  txMeta: {
    color: '#667085',
    fontSize: 12,
  },
  txHash: {
    color: '#98A2B3',
    fontSize: 12,
  },
  txLedger: {
    color: '#24495A',
    fontSize: 12,
    fontWeight: '900',
  },
  statusStrip: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    zIndex: 1,
  },
  statusDot: {
    backgroundColor: '#667085',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  statusDotActive: {
    backgroundColor: '#73D498',
  },
  statusText: {
    color: '#D6E8EF',
    flex: 1,
    fontSize: 12,
    lineHeight: 17,
  },
  appShell: {
    backgroundColor: '#F3F8FA',
    flex: 1,
  },
  appBody: {
    flex: 1,
  },
  appStatusStrip: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderTopColor: '#E4EEF2',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  bottomTabs: {
    backgroundColor: '#FFFFFF',
    borderTopColor: '#DCEAF0',
    borderTopWidth: 1,
    flexDirection: 'row',
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  bottomTab: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    gap: 2,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  bottomTabActive: {
    backgroundColor: '#E8F7F9',
  },
  bottomTabIcon: {
    color: '#7E909A',
    fontSize: 17,
    fontWeight: '900',
    lineHeight: 19,
  },
  bottomTabIconActive: {
    color: '#0F8EA3',
  },
  bottomTabText: {
    color: '#7E909A',
    fontSize: 10,
    fontWeight: '800',
  },
  bottomTabTextActive: {
    color: '#24495A',
  },
  sendHeader: {
    backgroundColor: '#0F8EA3',
    borderRadius: 8,
    gap: 6,
    padding: 16,
  },
  screenHeaderTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
  },
  screenHeaderSubtitle: {
    color: '#D6F1F4',
    fontSize: 13,
    lineHeight: 19,
  },
  backText: {
    color: '#D6F1F4',
    fontSize: 13,
    fontWeight: '900',
  },
  reviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 14,
    padding: 16,
  },
  receiveCard: {
    alignItems: 'stretch',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 14,
    padding: 16,
  },
  receiveQr: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#F1F7F9',
    borderColor: '#D8E7EC',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    height: 180,
    justifyContent: 'center',
    width: 180,
  },
  receiveQrText: {
    color: '#24495A',
    fontSize: 12,
    fontWeight: '900',
  },
  receiveQrMark: {
    color: '#0F8EA3',
    fontSize: 54,
    fontWeight: '900',
  },
  receiveQrHint: {
    color: '#667085',
    fontSize: 12,
    fontWeight: '800',
  },
  receiveAssetRow: {
    alignItems: 'center',
    borderBottomColor: '#E4EEF2',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 12,
  },
  successCard: {
    alignItems: 'stretch',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 14,
    padding: 18,
  },
  successIcon: {
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: '#BFEFDA',
    borderRadius: 40,
    borderWidth: 2,
    height: 80,
    justifyContent: 'center',
    width: 80,
  },
  successIconText: {
    color: '#0ABF73',
    fontSize: 38,
    fontWeight: '900',
  },
  successTitle: {
    color: '#24495A',
    fontSize: 28,
    fontWeight: '900',
    textAlign: 'center',
  },
  successSubtitle: {
    color: '#667085',
    fontSize: 13,
    textAlign: 'center',
  },
  buttonPair: {
    flexDirection: 'row',
    gap: 10,
  },
  transactionsHeader: {
    backgroundColor: '#0F8EA3',
    borderRadius: 8,
    gap: 16,
    padding: 14,
  },
  screenHeaderTitleLight: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  headerRefresh: {
    color: '#FFFFFF',
    fontSize: 21,
    fontWeight: '900',
    minWidth: 36,
    textAlign: 'center',
  },
  filterTabs: {
    flexDirection: 'row',
    gap: 8,
  },
  filterTab: {
    borderBottomColor: 'transparent',
    borderBottomWidth: 2,
    flex: 1,
    paddingBottom: 8,
  },
  filterTabSelected: {
    borderBottomColor: '#0ABF73',
  },
  filterTabText: {
    color: '#B8DDE3',
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  filterTabTextSelected: {
    color: '#FFFFFF',
  },
  swapCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 12,
    padding: 16,
  },
  swapInputRow: {
    alignItems: 'center',
    backgroundColor: '#F1F7F9',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    minHeight: 54,
    paddingHorizontal: 12,
  },
  swapInput: {
    color: '#24495A',
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
  },
  swapToken: {
    color: '#24495A',
    fontSize: 14,
    fontWeight: '900',
  },
  swapSwitch: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4EEF2',
    borderRadius: 8,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  swapSwitchText: {
    color: '#0F8EA3',
    fontSize: 22,
    fontWeight: '900',
  },
  swapAmountText: {
    color: '#24495A',
    flex: 1,
    fontSize: 18,
    fontWeight: '900',
  },
  rateRow: {
    alignItems: 'center',
    borderTopColor: '#E4EEF2',
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 12,
  },
  appRow: {
    alignItems: 'center',
    borderBottomColor: '#E4EEF2',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 12,
  },
  appIcon: {
    alignItems: 'center',
    backgroundColor: '#E8F7F9',
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  appIconLarge: {
    alignItems: 'center',
    backgroundColor: '#E8F7F9',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  appIconText: {
    color: '#0F8EA3',
    fontSize: 16,
    fontWeight: '900',
  },
  connectButton: {
    backgroundColor: '#E5FAF1',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  connectButtonText: {
    color: '#0ABF73',
    fontSize: 12,
    fontWeight: '900',
  },
  connectionSheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 14,
    padding: 16,
  },
  sheetTitle: {
    color: '#24495A',
    fontSize: 18,
    fontWeight: '900',
  },
  connectionIcons: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'center',
    paddingVertical: 16,
  },
  connectionDots: {
    color: '#B2C5CD',
    fontSize: 20,
    fontWeight: '900',
  },
});
