name = "privy-stellar-api"
main = "src/index.ts"
compatibility_date = "2026-06-09"
compatibility_flags = ["nodejs_compat"]

[vars]
ALLOWED_ORIGINS = "*"
HORIZON_TESTNET_URL = "https://horizon-testnet.stellar.org"
HORIZON_MAINNET_URL = "https://horizon.stellar.org"
FRIENDBOT_URL = "https://friendbot.stellar.org"
PAYMENT_API_BASE_URL = "https://payment-api.dev.seerbot.io"
PAYMENT_CALLBACK_URL = "https://privy-stellar-api.namvu3121.workers.dev/api/ramp/callback"
WALLETCONNECT_PROJECT_ID = ""

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "privy_stellar_db"
database_id = "582ba8ad-9a77-4330-a5f1-9b15afae4401"
