import { StyleSheet } from 'react-native';

export const modern = StyleSheet.create({
  screenFill: {
    flex: 1,
  },
  screen: {
    backgroundColor: 'transparent',
    flexGrow: 1,
    paddingBottom: 126,
  },
  portfolioRoot: {
    backgroundColor: '#000000',
    flex: 1,
  },
  portfolioBackgroundImage: {
    opacity: 0.98,
  },
  screenInset: {
    gap: 18,
    paddingBottom: 126,
  },
  hero: {
    backgroundColor: 'transparent',
    minHeight: 492,
    overflow: 'hidden',
  },
  heroMainnet: {
    minHeight: 380,
  },
  heroScrim: {
    backgroundColor: 'rgba(18, 42, 96, 0.12)',
    flex: 1,
    paddingBottom: 30,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  heroTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  heroIconButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(14, 31, 74, 0.22)',
    borderColor: 'rgba(255,255,255,0.24)',
    borderRadius: 20,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  heroIconText: {
    color: '#FFFFFF',
    fontSize: 29,
    fontWeight: '600',
  },
  networkPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(14, 31, 74, 0.24)',
    borderColor: 'rgba(255,255,255,0.24)',
    borderWidth: 1,
    borderRadius: 20,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 5,
    height: 40,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingLeft: 6,
    paddingRight: 8,
  },
  networkPillText: {
    color: '#FFFFFF',
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '800',
  },
  networkChevron: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 16,
    fontWeight: '800',
  },
  addressPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    height: 40,
    justifyContent: 'center',
    minWidth: 70,
    paddingHorizontal: 10,
  },
  addressPillText: {
    color: '#FFFFFF',
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '800',
  },
  heroActions: {
    flexDirection: 'row',
    gap: 6,
  },
  heroCard: {
    backgroundColor: 'transparent',
    marginTop: 42,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 0,
  },
  heroCardHeader: {
    alignItems: 'center',
    flexDirection: 'column',
    gap: 8,
    justifyContent: 'center',
  },
  heroValue: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingTop: 52,
  },
  heroLabel: {
    color: '#A1B0C8',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  heroNetworkMeta: {
    color: '#9AA7BA',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
    textAlign: 'center',
  },
  heroAmount: {
    color: '#FFFFFF',
    fontSize: 44,
    fontWeight: '900',
    letterSpacing: 0,
    marginTop: 16,
    textAlign: 'center',
  },
  heroPriceNote: {
    color: '#8A97AA',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 7,
    textAlign: 'center',
  },
  heroAccountRow: {
    alignItems: 'center',
    backgroundColor: '#F4F8FA',
    borderRadius: 20,
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
    padding: 10,
  },
  heroAccountMark: {
    alignItems: 'center',
    backgroundColor: '#B8FF45',
    borderRadius: 17,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  heroAccountMarkText: {
    color: '#000000',
    fontSize: 16,
    fontWeight: '900',
  },
  heroAccountCopy: {
    flex: 1,
    gap: 2,
  },
  heroAccountTitle: {
    color: '#17233D',
    fontSize: 13,
    fontWeight: '900',
  },
  heroSubValue: {
    color: '#71839B',
    fontSize: 12,
    fontWeight: '700',
  },
  heroNetworkBadge: {
    backgroundColor: '#B8FF45',
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  heroNetworkBadgeMainnet: {
    backgroundColor: '#EAF8F1',
  },
  heroNetworkBadgeText: {
    color: '#000000',
    fontSize: 10,
    fontWeight: '900',
  },
  heroNetworkBadgeTextMainnet: {
    color: '#0B9361',
  },
  quickGrid: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 36,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 28,
    paddingHorizontal: 12,
    paddingVertical: 18,
  },
  quickItem: {
    alignItems: 'center',
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  quickCircle: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  quickIcon: {
    color: '#FFFFFF',
    fontSize: 33,
    fontWeight: '500',
  },
  quickLabel: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  belowHero: {
    backgroundColor: 'transparent',
    gap: 16,
    marginTop: 10,
    paddingBottom: 24,
  },
  promoTrack: {
    gap: 12,
    paddingHorizontal: 18,
  },
  promoCard: {
    borderRadius: 18,
    gap: 10,
    minHeight: 128,
    padding: 18,
    width: 226,
  },
  promoIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.8)',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  promoIconText: {
    color: '#24495A',
    fontSize: 18,
    fontWeight: '900',
  },
  promoTitle: {
    color: '#24495A',
    fontSize: 17,
    fontWeight: '900',
  },
  promoTitleDark: {
    color: '#FFFFFF',
  },
  promoText: {
    color: '#7E909A',
    fontSize: 13,
    lineHeight: 18,
  },
  promoTextDark: {
    color: 'rgba(255,255,255,0.72)',
  },
  activateNotice: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginHorizontal: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  activateIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(184,255,69,0.12)',
    borderColor: 'rgba(184,255,69,0.26)',
    borderRadius: 18,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  activateCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  activateTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  activateText: {
    color: '#9AA7AE',
    flexShrink: 1,
    fontSize: 12,
    lineHeight: 17,
  },
  activateButton: {
    alignItems: 'center',
    backgroundColor: '#B8FF45',
    borderRadius: 17,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 14,
  },
  activateButtonText: {
    color: '#000000',
    fontSize: 12,
    fontWeight: '900',
  },
  sectionCard: {
    backgroundColor: 'transparent',
    gap: 6,
    marginHorizontal: 18,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  sectionHeaderActions: {
    flexDirection: 'row',
    gap: 8,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 19,
    fontWeight: '900',
  },
  sectionActionText: {
    color: '#B8FF45',
    fontSize: 13,
    fontWeight: '800',
  },
  sectionIconButton: {
    alignItems: 'center',
    backgroundColor: '#F3F5F8',
    borderRadius: 16,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  homeAssetGroup: {
    gap: 10,
    marginTop: 0,
  },
  homeAssetGroupMainnet: {
    marginTop: 0,
  },
  homeAssetGroupMainnetWithNotice: {
    marginTop: 0,
  },
  homeBannerWrap: {
    alignSelf: 'center',
    backgroundColor: '#05070A',
    borderRadius: 18,
    height: 86,
    marginTop: 12,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  homeBannerScroll: {
    flex: 1,
  },
  homeBannerImage: {
    height: '100%',
  },
  homeBannerDots: {
    alignItems: 'center',
    bottom: 10,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  homeBannerDot: {
    backgroundColor: 'rgba(255,255,255,0.42)',
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  homeBannerDotActive: {
    backgroundColor: '#B8FF45',
    width: 18,
  },
  assetTabsCard: {
    backgroundColor: 'transparent',
    gap: 8,
    marginHorizontal: 18,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  assetTabs: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 24,
    minHeight: 36,
  },
  assetTab: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    minHeight: 34,
  },
  assetTabText: {
    color: '#666A75',
    fontSize: 14,
    fontWeight: '900',
  },
  assetTabTextActive: {
    color: '#FFFFFF',
  },
  assetTabUnderline: {
    backgroundColor: 'transparent',
    borderRadius: 2,
    height: 2,
    marginTop: 7,
    width: 30,
  },
  assetTabUnderlineActive: {
    backgroundColor: '#B8FF45',
  },
  assetTabPanel: {
    gap: 0,
  },
  assetShowMoreButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(184,255,69,0.12)',
    borderColor: 'rgba(184,255,69,0.28)',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 12,
    minHeight: 36,
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  assetShowMoreText: {
    color: '#B8FF45',
    fontSize: 13,
    fontWeight: '900',
  },
  assetModernRow: {
    borderBottomColor: 'rgba(255,255,255,0.06)',
    borderBottomWidth: 1,
    gap: 10,
    paddingVertical: 14,
  },
  assetPressArea: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  tokenIcon: {
    alignItems: 'center',
    borderRadius: 18,
    justifyContent: 'center',
  },
  tokenIconText: {
    fontSize: 18,
    fontWeight: '900',
  },
  assetModernBody: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  assetNameLine: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    minWidth: 0,
  },
  assetModernName: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '900',
    flexShrink: 1,
  },
  assetBadge: {
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  assetBadgeDemo: {
    backgroundColor: '#EEF3F5',
  },
  assetBadgeTrustline: {
    backgroundColor: '#FFF5E7',
  },
  assetBadgeUnverified: {
    backgroundColor: '#FFF1F3',
  },
  assetBadgeVerified: {
    backgroundColor: '#E7F9F1',
  },
  assetBadgeText: {
    fontSize: 10,
    fontWeight: '900',
  },
  assetBadgeTextDemo: {
    color: '#536873',
  },
  assetBadgeTextTrustline: {
    color: '#A86200',
  },
  assetBadgeTextUnverified: {
    color: '#C01048',
  },
  assetBadgeTextVerified: {
    color: '#0ABF73',
  },
  assetModernMeta: {
    color: '#8B99A3',
    fontSize: 14,
    flexShrink: 1,
  },
  assetModernRight: {
    alignItems: 'flex-end',
    gap: 2,
    maxWidth: 112,
  },
  assetModernBalance: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'right',
  },
  assetModernCode: {
    color: '#9AA7AE',
    fontSize: 12,
    fontWeight: '800',
  },
  assetFaucetButton: {
    alignSelf: 'flex-end',
    backgroundColor: '#E7F9F1',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  assetAddButton: {
    alignSelf: 'flex-end',
    backgroundColor: '#EEF3F5',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  assetButtonText: {
    color: '#0ABF73',
    fontSize: 13,
    fontWeight: '900',
  },
  collectibleModernRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(255,255,255,0.06)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 14,
    minHeight: 76,
    paddingVertical: 14,
  },
  collectibleActionButton: {
    alignSelf: 'center',
    flexShrink: 0,
  },
  assetSelectButton: {
    alignItems: 'center',
    backgroundColor: '#161922',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 82,
    padding: 14,
  },
  assetSelectCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  assetSelectEmptyIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 21,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  assetSelectLabel: {
    color: '#A1B0C8',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  assetSelectMeta: {
    color: '#A1B0C8',
    fontSize: 12,
    fontWeight: '700',
  },
  assetSelectPrice: {
    color: '#A1B0C8',
    fontSize: 11,
    fontWeight: '800',
  },
  assetSelectRight: {
    alignItems: 'flex-end',
    gap: 3,
    maxWidth: 94,
  },
  assetSelectTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '900',
  },
  assetSelectValue: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
  },
  assetPickerBalance: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  assetPickerBody: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  assetPickerClose: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  assetPickerCode: {
    color: '#FFFFFF',
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '900',
    minWidth: 0,
  },
  assetPickerEmpty: {
    alignItems: 'center',
    gap: 6,
    padding: 28,
  },
  assetPickerFilter: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 16,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  assetPickerFilterActive: {
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  assetPickerFilterText: {
    color: '#A1B0C8',
    fontSize: 12,
    fontWeight: '900',
  },
  assetPickerFilterTextActive: {
    color: '#FFFFFF',
  },
  assetPickerFilters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  assetPickerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  assetPickerList: {
    marginTop: 6,
  },
  assetPickerMeta: {
    color: '#A1B0C8',
    fontSize: 11,
    fontWeight: '700',
    minWidth: 0,
  },
  assetPickerName: {
    color: '#A1B0C8',
    fontSize: 12,
    fontWeight: '800',
    minWidth: 0,
  },
  assetPickerOverlay: {
    backgroundColor: 'rgba(5,16,25,0.42)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  assetPickerPressArea: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
  },
  assetPickerPrice: {
    color: '#A1B0C8',
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'right',
  },
  assetPickerRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(255,255,255,0.06)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 76,
    paddingHorizontal: 2,
    paddingVertical: 12,
  },
  assetPickerRowDisabled: {
    opacity: 0.5,
  },
  assetPickerRowSelected: {
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  assetPickerSearch: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  assetPickerSearchInput: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    paddingVertical: 10,
  },
  assetPickerSheet: {
    backgroundColor: '#111318',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    gap: 14,
    maxHeight: '88%',
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  assetPickerSubtitle: {
    color: '#A1B0C8',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 2,
  },
  assetPickerTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
  },
  assetPickerTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    minWidth: 0,
  },
  assetPickerTrailing: {
    alignItems: 'flex-end',
    flexShrink: 0,
    gap: 6,
    justifyContent: 'center',
    width: 88,
  },
  assetPickerValueArea: {
    alignItems: 'flex-end',
    gap: 3,
    minHeight: 38,
    width: '100%',
  },
  tabBarWrap: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
  },
  tabBar: {
    backgroundColor: '#05070A',
    borderTopColor: 'rgba(255,255,255,0.05)',
    borderTopWidth: 1,
    flexDirection: 'row',
    minHeight: 88,
    paddingBottom: 24,
    paddingTop: 12,
  },
  tabIndicator: {
    backgroundColor: '#B8FF45',
    borderRadius: 2,
    height: 3,
    shadowColor: '#B8FF45',
    shadowOffset: { height: 0, width: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    top: -1,
    width: 36,
  },
  tabPress: {
    flex: 1,
  },
  tabItem: {
    alignItems: 'center',
    flex: 1,
    gap: 2,
    justifyContent: 'center',
  },
  tabIcon: {
    color: '#8A9AA3',
    fontSize: 20,
    fontWeight: '900',
  },
  tabIconActive: {
    color: '#B8FF45',
  },
  tabIconWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIconWrapActive: {
    opacity: 1,
  },
  tabText: {
    color: '#8A9AA3',
    fontSize: 11,
    fontWeight: '800',
  },
  tabTextActive: {
    color: '#B8FF45',
  },
  appStatus: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderColor: '#E4EEF2',
    borderRadius: 20,
    borderWidth: 1,
    bottom: 98,
    flexDirection: 'row',
    gap: 8,
    left: 18,
    paddingHorizontal: 12,
    paddingVertical: 9,
    position: 'absolute',
    right: 18,
  },
  statusText: {
    color: '#6A7E88',
    flex: 1,
    fontSize: 12,
  },
  tokenPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tokenPill: {
    backgroundColor: '#EEF3F5',
    borderRadius: 18,
    paddingHorizontal: 15,
    paddingVertical: 9,
  },
  tokenPillActive: {
    backgroundColor: '#0F8EA3',
  },
  tokenPillText: {
    color: '#536873',
    fontSize: 13,
    fontWeight: '900',
  },
  tokenPillTextActive: {
    color: '#FFFFFF',
  },
  modernHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginHorizontal: 18,
    marginTop: 16,
  },
  backButton: {
    alignItems: 'center',
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 20,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  backButtonText: {
    color: '#24495A',
    fontSize: 34,
    fontWeight: '600',
    lineHeight: 40,
  },
  modernHeaderCopy: {
    flex: 1,
    gap: 3,
  },
  modernHeaderTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
  },
  modernHeaderSubtitle: {
    color: '#A1B0C8',
    fontSize: 13,
    lineHeight: 18,
  },
  formCard: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginHorizontal: 18,
    padding: 20,
  },
  swapFormCard: {
    marginHorizontal: 14,
    padding: 8,
  },
  swapBox: {
    backgroundColor: '#10120F',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 24,
    borderWidth: 1,
    gap: 8,
    padding: 8,
    position: 'relative',
  },
  swapField: {
    backgroundColor: '#1B1D1A',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
    minHeight: 112,
    paddingHorizontal: 14,
    paddingVertical: 14,
    zIndex: 2,
  },
  swapFieldTop: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  swapReceiveField: {
    paddingTop: 14,
  },
  swapLabel: {
    color: '#CAD4BE',
    flexShrink: 0,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  swapBalanceRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'flex-end',
    minWidth: 0,
  },
  swapBalanceText: {
    color: '#CAD4BE',
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.1,
    minWidth: 0,
    textAlign: 'right',
  },
  swapMaxText: {
    color: '#B8FF45',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  swapAssetRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  swapTokenPill: {
    alignItems: 'center',
    backgroundColor: '#2B2D2A',
    borderRadius: 24,
    flexDirection: 'row',
    gap: 7,
    maxWidth: 132,
    minWidth: 112,
    paddingBottom: 6,
    paddingLeft: 6,
    paddingRight: 10,
    paddingTop: 6,
  },
  swapTokenText: {
    color: '#F1F3F0',
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  swapAmountInput: {
    color: '#F1F3F0',
    flex: 1,
    fontSize: 32,
    fontWeight: '900',
    minHeight: 46,
    minWidth: 0,
    padding: 0,
    textAlign: 'right',
  },
  swapAmountValue: {
    color: '#F1F3F0',
    flex: 1,
    fontSize: 32,
    fontWeight: '900',
    minHeight: 46,
    minWidth: 0,
    textAlign: 'right',
  },
  swapMiddleButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#3B3D39',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 15,
    borderWidth: 3,
    height: 50,
    justifyContent: 'center',
    width: 50,

  },
  swapMiddleText: {
    color: '#0F8EA3',
    fontSize: 23,
    fontWeight: '900',
  },
  rateCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  primaryModernButton: {
    alignItems: 'center',
    backgroundColor: '#B8FF45',
    borderRadius: 18,
    flex: 1,
    minHeight: 54,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  secondaryModernButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
    flex: 1,
    minHeight: 52,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  modernButtonText: {
    color: '#05070A',
    fontSize: 16,
    fontWeight: '900',
  },
  secondaryModernButtonText: {
    color: '#FFFFFF',
  },
  segmented: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  segmentItem: {
    alignItems: 'center',
    borderRadius: 14,
    flex: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  segmentItemActive: {
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  segmentItemPressed: {
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  segmentText: {
    color: '#A1B0C8',
    fontSize: 13,
    fontWeight: '900',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  txModernRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(255,255,255,0.06)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 14,
  },
  txModernBody: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  txModernTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    flexShrink: 1,
  },
  txModernMeta: {
    color: '#A1B0C8',
    fontSize: 12,
    flexShrink: 1,
  },
  txModernAmount: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '900',
    maxWidth: 122,
    textAlign: 'right',
  },
  txAmountPositive: {
    color: '#B8FF45',
  },
  txAmountNegative: {
    color: '#FF455A',
  },
  emptyModern: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 22,
    gap: 6,
    padding: 22,
  },
  emptyModernTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  emptyModernText: {
    color: '#A1B0C8',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  infoBlock: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 20,
    gap: 7,
    padding: 14,
  },
  infoLabel: {
    color: '#A1B0C8',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  infoValue: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
  },
  infoRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  infoRowValue: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  activeWalletCard: {
    alignItems: 'center',
    backgroundColor: '#EAF7FA',
    borderColor: '#C5E9EF',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 16,
  },
  walletOrb: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  activeWalletName: {
    color: '#24495A',
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  activeWalletAddress: {
    color: '#667985',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  walletBadge: {
    backgroundColor: '#E7F9F1',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  walletBadgeText: {
    color: '#0ABF73',
    fontSize: 12,
    fontWeight: '900',
  },
  walletListRow: {
    borderColor: '#E4EEF2',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 12,
  },
  walletListTop: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  walletListIcon: {
    alignItems: 'center',
    backgroundColor: '#EAF7FA',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  walletListBody: {
    flex: 1,
    gap: 4,
  },
  walletNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  walletListName: {
    color: '#24495A',
    flex: 1,
    fontSize: 16,
    fontWeight: '900',
  },
  walletListMeta: {
    color: '#7E909A',
    fontSize: 12,
    fontWeight: '800',
  },
  walletActiveBadge: {
    backgroundColor: '#E7F9F1',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  walletActiveText: {
    color: '#0ABF73',
    fontSize: 11,
    fontWeight: '900',
  },
  walletRenameInput: {
    backgroundColor: '#F4F8FA',
    borderColor: '#D8E7EC',
    borderRadius: 8,
    borderWidth: 1,
    color: '#24495A',
    fontSize: 14,
    fontWeight: '800',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  walletActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  walletMiniButton: {
    backgroundColor: '#EAF7FA',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  walletMiniButtonText: {
    color: '#0F8EA3',
    fontSize: 12,
    fontWeight: '900',
  },
  walletArchiveButton: {
    backgroundColor: '#FFF1F3',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  walletArchiveText: {
    color: '#C01048',
    fontSize: 12,
    fontWeight: '900',
  },
  walletButtons: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
  signOutButton: {
    alignItems: 'center',
    backgroundColor: '#FFF0F2',
    borderRadius: 22,
    flex: 1,
    minHeight: 52,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  signOutText: {
    color: '#D84C5F',
    fontSize: 16,
    fontWeight: '900',
  },
  explorerButton: {
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  explorerText: {
    color: '#B8FF45',
    fontSize: 13,
    fontWeight: '900',
  },
  faucetRow: {
    alignItems: 'center',
    borderBottomColor: '#EDF2F4',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 14,
    paddingVertical: 14,
  },
  disabledActionRow: {
    alignItems: 'center',
    backgroundColor: '#F4F8FA',
    borderColor: '#E2EBEF',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    opacity: 0.78,
    padding: 14,
  },
  successOrb: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(184,255,69,0.15)',
    borderColor: 'rgba(184,255,69,0.3)',
    borderRadius: 42,
    borderWidth: 1,
    height: 84,
    justifyContent: 'center',
    width: 84,
  },
  successOrbText: {
    color: '#B8FF45',
    fontSize: 42,
    fontWeight: '900',
  },
  successModernTitle: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '900',
    textAlign: 'center',
  },
  successModernText: {
    color: '#A1B0C8',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  swapConfirmOverlay: {
    backgroundColor: 'rgba(0,0,0,0.66)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  swapConfirmBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  swapConfirmSheet: {
    backgroundColor: '#151715',
    borderColor: 'rgba(255,255,255,0.08)',
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderWidth: 1,
    gap: 14,
    paddingHorizontal: 10,
    paddingTop: 10,
    zIndex: 1,
  },
  swapConfirmHandle: {
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 3,
    height: 4,
    marginBottom: 2,
    width: 32,
  },
  swapConfirmHeader: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 24,
    position: 'relative',
  },
  swapConfirmTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  swapConfirmClose: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 12,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  swapConfirmCloseSlot: {
    alignItems: 'flex-end',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    top: 0,
    width: 32,
  },
  swapConfirmAmounts: {
    alignItems: 'center',
    gap: 4,
    paddingTop: 10,
  },
  swapConfirmAmount: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 30,
    maxWidth: '86%',
    textAlign: 'center',
  },
  swapConfirmReceiveAmount: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 26,
    maxWidth: '86%',
    textAlign: 'center',
  },
  swapConfirmTokenBadge: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.06)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  swapConfirmTokenText: {
    color: '#AEB7AD',
    fontSize: 8,
    fontWeight: '900',
  },
  swapConfirmArrowCircle: {
    alignItems: 'center',
    backgroundColor: 'rgba(184,255,69,0.12)',
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    marginVertical: 3,
    width: 32,
  },
  swapConfirmDetails: {
    backgroundColor: '#1C1F1A',
    borderColor: 'rgba(184,255,69,0.22)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 9,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  swapConfirmDetailRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  swapConfirmDetailLabel: {
    color: '#AEB7AD',
    flexShrink: 0,
    fontSize: 11,
    fontWeight: '700',
  },
  swapConfirmDetailValue: {
    color: '#FFFFFF',
    flex: 1,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'right',
  },
  swapConfirmPositiveValue: {
    color: '#B8FF45',
  },
  swapConfirmRouteLabel: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
  },
  swapConfirmNote: {
    color: '#8C948D',
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 13,
    paddingHorizontal: 12,
    textAlign: 'center',
  },
  swapConfirmButton: {
    alignItems: 'center',
    backgroundColor: '#B8FF00',
    borderRadius: 6,
    justifyContent: 'center',
    minHeight: 38,
  },
  swapConfirmButtonText: {
    color: '#111600',
    fontSize: 14,
    fontWeight: '900',
  },
  reviewModernBox: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 20,
    gap: 5,
    padding: 14,
  },
  reviewModernTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  reviewModernText: {
    color: '#A1B0C8',
    fontSize: 13,
    lineHeight: 18,
  },
  modernInput: {
    backgroundColor: '#1E232B',
    borderColor: '#2A303A',
    borderRadius: 20,
    borderWidth: 1,
    color: '#FFFFFF',
    fontSize: 16,
    minHeight: 56,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  assetSearchInput: {
    height: 44,
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  qrCard: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#F4F8FA',
    borderColor: '#DFE9ED',
    borderRadius: 28,
    borderWidth: 1,
    gap: 8,
    height: 192,
    justifyContent: 'center',
    width: 192,
  },
  qrMark: {
    color: '#0F8EA3',
    fontSize: 62,
    fontWeight: '900',
  },
  qrTinyText: {
    color: '#7E909A',
    fontSize: 12,
    fontWeight: '900',
  },
});
