import { StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  background: {
    flex: 1,
  },
  backgroundImage: {
    opacity: 1,
  },
  backdrop: {
    backgroundColor: 'rgba(3, 12, 24, 0.28)',
    flex: 1,
  },
  content: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 28,
  },
  hero: {
    gap: 25,
    paddingHorizontal: 22,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  brandMark: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderColor: 'rgba(255,255,255,0.58)',
    borderRadius: 14,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    width: 44,
  },
  brandCopy: {
    flex: 1,
  },
  brandName: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  brandMeta: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 1,
  },
  heroTextBlock: {
    gap: 7,
    paddingHorizontal: 2,
  },
  eyebrow: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.4,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: -0.8,
    lineHeight: 37,
  },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.76)',
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 315,
  },
  loginGroup: {
    gap: 20,
    width: '100%',
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 26,
    marginHorizontal: 16,
    paddingBottom: 22,
    paddingHorizontal: 18,
    paddingTop: 20,
    shadowColor: '#000000',
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 30,
  },
  stepHeader: {
    gap: 5,
    marginBottom: 18,
  },
  stepKicker: {
    color: '#2D5FC6',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  },
  stepTitle: {
    color: '#111318',
    fontSize: 27,
    fontWeight: '800',
    letterSpacing: -0.7,
    lineHeight: 32,
  },
  stepSubtitle: {
    color: '#737985',
    fontSize: 14,
    lineHeight: 20,
  },
  form: {
    gap: 12,
  },
  inputLabel: {
    color: '#343942',
    fontSize: 13,
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#F5F6F8',
    borderColor: '#E5E7EB',
    borderRadius: 16,
    borderWidth: 1,
    color: '#111318',
    fontSize: 16,
    minHeight: 54,
    paddingHorizontal: 16,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#111318',
    borderRadius: 16,
    flexDirection: 'row',
    gap: 9,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: 16,
  },
  primaryButtonDisabled: {
    backgroundColor: '#D9DCE1',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  primaryButtonTextDisabled: {
    color: '#878C95',
  },
  googleButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D9DCE1',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: 14,
  },
  googleButtonDisabled: {
    backgroundColor: '#F5F6F8',
  },
  googleText: {
    color: '#20242B',
    fontSize: 15,
    fontWeight: '700',
  },
  disabledText: {
    color: '#878C95',
  },
  divider: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginVertical: 2,
  },
  dividerLine: {
    backgroundColor: '#E7E9ED',
    flex: 1,
    height: 1,
  },
  dividerText: {
    color: '#9297A0',
    fontSize: 12,
    fontWeight: '700',
  },
  otpWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'space-between',
    minHeight: 56,
    position: 'relative',
  },
  otpHiddenInput: {
    height: 1,
    opacity: 0.01,
    position: 'absolute',
    width: 1,
  },
  otpCell: {
    alignItems: 'center',
    backgroundColor: '#F5F6F8',
    borderColor: '#E2E5E9',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    height: 54,
    justifyContent: 'center',
  },
  otpCellActive: {
    borderColor: '#111318',
    borderWidth: 2,
  },
  otpCellFilled: {
    backgroundColor: '#F0F1F3',
    borderColor: '#ADB2BA',
  },
  otpDigit: {
    color: '#101828',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 26,
  },
  sentBox: {
    backgroundColor: '#F5F6F8',
    borderColor: '#E7E9ED',
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
    marginBottom: 12,
    padding: 13,
  },
  sentLabel: {
    color: '#777D87',
    fontSize: 12,
    fontWeight: '700',
  },
  sentEmail: {
    color: '#111318',
    fontSize: 15,
    fontWeight: '800',
  },
  linkRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  textButton: {
    borderRadius: 8,
    paddingVertical: 8,
  },
  textButtonText: {
    color: '#20242B',
    fontSize: 13,
    fontWeight: '800',
  },
  messageBox: {
    alignItems: 'flex-start',
    backgroundColor: '#FFF1F2',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
    padding: 11,
  },
  errorText: {
    color: '#B42318',
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  safe: {
    backgroundColor: 'transparent',
    flex: 1,
  },
  googleIcon: {
    height: 21,
    width: 21,
  },
  brandImage: {
    height: 24,
    width: 24,
  },
});
