import { StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  root: {
    backgroundColor: 'transparent',
    flexGrow: 1,
  },
  background: {
    flex: 1,
  },
  backgroundImage: {
    opacity: 0.98,
  },
  backdrop: {
    backgroundColor: 'rgba(12, 31, 64, 0.18)',
    flex: 1,
  },
  hero: {
    justifyContent: 'space-between',
    minHeight: 286,
    padding: 22,
    paddingBottom: 34,
    paddingTop: 12,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  brandMark: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(255,255,255,0.74)',
    borderRadius: 8,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  brandMarkText: {
    color: '#3867D6',
    fontSize: 22,
    fontWeight: '900',
  },
  brandCopy: {
    flex: 1,
  },
  brandName: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  brandMeta: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 2,
  },
  heroTextBlock: {
    gap: 10,
  },
  eyebrow: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 40,
  },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 300,
  },
  statusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  statusPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderColor: 'rgba(255,255,255,0.24)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  statusDot: {
    backgroundColor: '#AAB6C5',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  statusDotActive: {
    backgroundColor: '#54E5A5',
  },
  statusText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius:18,
    borderTopRightRadius: 18,
    borderRadius: 18,
    minHeight: 430,
    padding: 22,
    paddingBottom: 30,
  },
  stepHeader: {
    gap: 8,
    marginBottom: 22,
  },
  stepKicker: {
    color: '#3867D6',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  stepTitle: {
    color: '#101828',
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 34,
  },
  stepSubtitle: {
    color: '#667085',
    fontSize: 15,
    lineHeight: 22,
  },
  form: {
    gap: 13,
  },
  inputLabel: {
    color: '#253142',
    fontSize: 13,
    fontWeight: '900',
  },
  input: {
    backgroundColor: '#F8FAFC',
    borderColor: '#D7E2EA',
    borderRadius: 20,
    borderWidth: 1,
    color: '#101828',
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#3867D6',
    borderRadius: 20,
    flexDirection: 'row',
    gap: 9,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 16,
  },
  primaryButtonDisabled: {
    backgroundColor: '#D4DCE8',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  primaryButtonTextDisabled: {
    color: '#7D8796',
  },
  googleButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D7E2EA',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: 14,
  },
  googleButtonDisabled: {
    backgroundColor: '#F1F5F9',
  },
  googleText: {
    color: '#172033',
    fontSize: 15,
    fontWeight: '900',
  },
  disabledText: {
    color: '#7D8796',
  },
  divider: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginVertical: 2,
  },
  dividerLine: {
    backgroundColor: '#E4EAF0',
    flex: 1,
    height: 1,
  },
  dividerText: {
    color: '#7B8794',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  otpWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'space-between',
    minHeight: 56,
    position: 'relative',
  },
  otpHiddenInput: {
    height: 1,
    opacity: 0.01,
    position: 'absolute',
    width: 1,
  },
  otpCell: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#D7E2EA',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    height: 54,
    justifyContent: 'center',
  },
  otpCellActive: {
    borderColor: '#3867D6',
    borderWidth: 2,
  },
  otpCellFilled: {
    backgroundColor: '#EEF4FF',
    borderColor: '#7CA3F5',
  },
  otpDigit: {
    color: '#101828',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 26,
  },
  sentBox: {
    backgroundColor: '#F8FAFC',
    borderColor: '#E0E8EF',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    marginBottom: 12,
    padding: 13,
  },
  sentLabel: {
    color: '#667085',
    fontSize: 12,
    fontWeight: '900',
  },
  sentEmail: {
    color: '#101828',
    fontSize: 15,
    fontWeight: '900',
  },
  linkRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  textButton: {
    borderRadius: 8,
    paddingVertical: 8,
  },
  textButtonText: {
    color: '#3867D6',
    fontSize: 13,
    fontWeight: '900',
  },
  messageBox: {
    backgroundColor: '#F3F7FB',
    borderColor: '#E0E8EF',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    marginTop: 18,
    padding: 12,
  },
  messageInset: {
    paddingBottom: 24,
    paddingHorizontal: 22,
  },
  messageText: {
    color: '#475467',
    fontSize: 13,
    lineHeight: 20,
  },
  errorText: {
    color: '#B42318',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },
  safe: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  googleIcon: {
    height: 24,
    width: 24,
  },
  brandImage: {
    height: 24,
    width: 24,
  },
});
